backend/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
# from django.conf.urls import url 
from backend import views

app_name = 'backend'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('register', views.register, name='register'),
    path('logout_view-page/', views.logout_view, name='logout_view'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('products/', views.product_list, name='product-list'),
    path('products/add/', views.add_product, name='add-product'),
    path('delete_products/', views.del_products, name='del_products'),
    path('view_products_details/<int:view_id>', views.view_products_details, name='view_products_details'),
    path('products/edit/<int:pk>/', views.edit_product, name='edit-product'),
    path('products/delete/<int:pk>/', views.delete_product, name='delete-product'),
    path('users/', views.user_list, name='user-list'),
    path('users/add/', views.add_user, name='add-user'),
    path('users/edit/<int:pk>/', views.edit_user, name='edit-user'),
    path('users/delete/<int:pk>/', views.delete_user, name='delete-user'),
    path('view-orders', views.view_orders, name='view_orders'),
    path('account', views.account, name='account'),
    path('edit-account/<int:pk>/', views.edit_account, name='edit_account'),
    path('delete-account', views.delete_account, name='delete_account'),
    path('account-change-password', views.change_password, name='change_password'),
    path('account/delete/', views.delete_account, name='delete-account'),
    path('my-wishlist', views.wishlist_view, name='wish'),
    path('wishlist/remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('cart/remove/<int:product_id>/', views.remove_cart, name='remove_from_cart'),
    path("checkout/", views.checkout, name="checkout"),
    path("checkout/process/", views.process_checkout, name="process_checkout"),
#     path('product-image/<int:pk>/delete/', views.delete_product_image, name='delete_product_image'),


    # Password reset
    path('password_reset/', views.password_reset_request, name='password_reset_request'),


]

frontend/urls.py
from django.urls import path
# from django.conf.urls import url 
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.about, name='about'),
    path('product', views.product, name='product'),
    path('gadgets_detail/<int:product_id>/', views.product_details, name='product_details'),
    path('contact', views.contact, name='contact'),
    # path('cart', views.cart, name='cart'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle-wishlist'),
    path('load-more-products/', views.load_more_products, name='load_more_products'),
    path("search/", views.search_products, name="search-products"),




]

nomad_camel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url 

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', include('frontend.urls')),
    path('auth/', include('backend.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='backend/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='backend/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='backend/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# nomad_camel/urls.py

handler404 = 'nomad_camel.views.custom_404_view'

frontend/models.py
from django.db import models

from django.db import models
import os


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    main_image = models.ImageField(upload_to="product_images/", blank=True, null=True)  # main image
    hot = models.BooleanField(default=False)
    daily_deal = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        # Delete the main image file if it exists
        if self.main_image and os.path.isfile(self.main_image.path):
            os.remove(self.main_image.path)
        super().delete(*args, **kwargs)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product_images/")

    def __str__(self):
        return f"Image for {self.product.name}"

    def delete(self, *args, **kwargs):
        # Delete the gallery image file if it exists
        if self.image and os.path.isfile(self.image.path):
            os.remove(self.image.path)
        super().delete(*args, **kwargs)

frontend/views.py
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from frontend.models import *
from backend.models import*
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    all_products = Product.objects.order_by('-created_at')
    hot_products = Product.objects.filter(hot=True)
    daily_deals = Product.objects.filter(daily_deal=True)
    
    return render(request, 'frontend/index.html', {'pro': all_products,'hot': hot_products,'deals': daily_deals,})
def about(request):
    return render(request, 'frontend/about.html')

def product(request):
    products = Product.objects.order_by('-created_at')
    paginator = Paginator(products, 8) 

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'frontend/product.html', {'page_obj': page_obj})

def product_details(request, product_id):
    product_detail =Product.objects.get(id=product_id)
    return render(request, 'frontend/product-detail.html', {'det':product_detail})


def contact(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        message = request.POST.get('msg')  # match your form field name

        subject = 'Contact Us - NOMAD CAMEL'
        context = {
            'email': email,
            'message': message,
        }
        html_message = render_to_string('frontend/mail-template.html', context)
        plain_message = strip_tags(html_message)
        from_email = 'NOMAD-CAMEL <nomadcamelngpb@gmail.com>'
        recipient_list = [email]  

        try:
            send_mail(subject, plain_message, from_email, recipient_list, html_message=html_message)
            messages.success(request, 'Email sent, you will receive a response shortly!')
        except Exception as e:
            messages.error(request, f'Mail not sent. Error: {str(e)}')

    return render(request, 'frontend/contact.html')


def toggle_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist, created = Wishlist.objects.get_or_create(user=request.user, product=product)
    if not created:
        # Already exists, so remove it from the wishlist.
        wishlist.delete()
        status = 'removed'
    else:
        status = 'added'
    return JsonResponse({'status': status})


def load_more_products(request):
    page = int(request.GET.get('page', 1))
    per_page = 6  # or however many you want to load per click

    products = Product.objects.all()
    paginator = Paginator(products, per_page)

    try:
        page_obj = paginator.page(page)
    except:
        return JsonResponse({'products': [], 'has_next': False})

    data = []
    for product in page_obj:
        data.append({
            'id': product.id,
            'name': product.name,
            'price': product.price,
            'image_url': product.image.url if product.image else '',
        })

    return JsonResponse({
        'products': data,
        'has_next': page_obj.has_next()
    })



def search_products(request):
    query = request.GET.get('q', '')
    products = Product.objects.all()

    if query:
        products = products.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )

    context = {
        'products': products,
        'query': query,
    }
    return render(request, 'frontend/search-results.html', context)

templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
NOMAD-CAMEL
{% endblock %}

{% block content %}

<!-- Slider -->
<section class="section-slide">
	<div class="wrap-slick1">
		<div class="slick1">
			<div class="item-slick1">
				<div class="container h-full">
					<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">

					</div>
				</div>
			</div>
		</div>
	</div>
</section>


<!-- Banner -->
<div class="sec-banner bg0 p-t-80 p-b-50">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
				<!-- Block1 -->
				<div class="block1 wrap-pic-w">
					<img src="{% static 'frontend/images/DSC99BHFJF.png' %}" alt="IMG-BANNER"
						style="width: auto; height: 380px;">

					<a href="{% url 'frontend:product' %}"
						class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
						<div class="block1-txt-child1 flex-col-l">
							<!-- <span class="block1-name ltext-102 trans-04 p-b-8">
								Power Bank
							</span>

							<span class="block1-info stext-102 trans-04">
								Spring 2018
							</span> -->
						</div>

						<div class="block1-txt-child2 p-b-4 trans-05">
							<div class="block1-link stext-101 cl0 trans-09">
								Shop Now
							</div>
						</div>
					</a>
				</div>
			</div>

			<div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
				<!-- Block1 -->
				<div class="block1 wrap-pic-w">
					<img src="{% static 'frontend/images/banner-02.jpg' %}" alt="IMG-BANNER"
						style="width: auto; height: 380px;">

					<a href="{% url 'frontend:product' %}"
						class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
						<div class="block1-txt-child1 flex-col-l">
							<!-- <span class="block1-name ltext-102 trans-04 p-b-8">
								Power Bank
							</span>

							<span class="block1-info stext-102 trans-04">
								Spring 2018
							</span> -->
						</div>

						<div class="block1-txt-child2 p-b-4 trans-05">
							<div class="block1-link stext-101 cl0 trans-09">
								Shop Now
							</div>
						</div>
					</a>
				</div>
			</div>

			<div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
				<!-- Block1 -->
				<div class="block1 wrap-pic-w">
					<img src="{% static 'frontend/images/DSC99BHFJF3.jpeg' %}" alt="IMG-BANNER"
						style="width: auto; height: 380px;">

					<a href="{% url 'frontend:product' %}"
						class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
						<div class="block1-txt-child1 flex-col-l">
							<!-- <span class="block1-name ltext-102 trans-04 p-b-8">
								Power Bank
							</span>

							<span class="block1-info stext-102 trans-04">
								New Trend
							</span> -->
						</div>

						<div class="block1-txt-child2 p-b-4 trans-05">
							<div class="block1-link stext-101 cl0 trans-09">
								Shop Now
							</div>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Product -->
<section class="bg0 p-t-23 p-b-140">
  <div class="container">
    <div class="p-b-10">
      <h3 class="ltext-103 cl5">
        Product Overview
      </h3>
    </div>

    <div class="flex-w flex-sb-m p-b-52">
      <!-- Filter Buttons -->
      <div class="flex-w flex-l-m filter-tope-group m-tb-10">
        <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">All Products</button>
        <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".women">Hot & New</button>
        <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".men">Daily Deal</button>
      </div>

      <!-- Search -->
      	<div class="flex-w flex-c-m m-tb-10">
			<div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
				<i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
				<i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
				Search
			</div>
      	</div>

      <!-- Search Panel -->
     <!-- Search Panel -->
        <div class="dis-none panel-search w-full p-t-10 p-b-15">
          <form method="get" action="{% url 'frontend:search-products' %}" class="bor8 dis-flex p-l-15 w-full">
            <button type="submit" class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
              <i class="zmdi zmdi-search"></i>
            </button>
            <input 
              class="mtext-107 cl2 size-114 plh2 p-r-15" 
              type="text" 
              name="q" 
			  value="{{ request.GET.q|default:'' }}"
              placeholder="Search products..."
              required
            >
          </form>
        </div>

    </div>

    <!-- PRODUCTS GRID -->
    <div class="row isotope-grid">
      {% if pro %}
        {% for p in pro %}
          <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women">
            <div class="block2">
              <div class="block2-pic hov-img0" style="height: 310px;">
                <img src="{{ p.main_image.url }}" alt="{{ p.name }}" style="width: 100%; height: 100%; object-fit: cover;">

                <a href="{% url 'frontend:product_details' p.id %}"
                  class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04">
                  Quick View
                </a>
              </div>

              <div class="block2-txt flex-w flex-t p-t-14">
                <div class="block2-txt-child1 flex-col-l">
                  <a href="#" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                    {{ p.name }}
                  </a>

                  <span class="stext-105 cl3">₦{{ p.price }}</span>
                </div>

                <div class="block2-txt-child2 flex-r p-t-3">
                  <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2" data-id="{{ p.id }}">
                    <img class="icon-heart1 dis-block trans-04"
                        src="{% static 'frontend/images/icons/icon-heart-01.png' %}" alt="ICON">
                    <img class="icon-heart2 dis-block trans-04 ab-t-l"
                        src="{% static 'frontend/images/icons/icon-heart-02.png' %}" alt="ICON">
                  </a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="alert alert-info text-center">No products available at the moment.</div>
      {% endif %}
    </div>

    <!-- Load More Button -->
    <div class="flex-c-m flex-w w-full p-t-45">
      <a href="{% url 'frontend:product' %}" id="load-more-btn" class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04">
        View More
      </a>
    </div>
  </div>
</section>

<script>
	// Wait for DOM content to load
	document.addEventListener("DOMContentLoaded", function () {
		// Attach click event listeners to all wishlist toggle buttons
		document.querySelectorAll('.js-addwish-b2').forEach(function (btn) {
			btn.addEventListener('click', function (e) {
				e.preventDefault();
				const productId = this.getAttribute('data-id');
				const currentBtn = this;

				fetch("{% url 'frontend:toggle-wishlist' 0 %}".replace('/0/', '/' + productId + '/'))
					.then(response => response.json())
					.then(data => {
						if (data.status === 'added') {
							// Optionally toggle a class to show 'active' state (filled heart)
							currentBtn.classList.add('active');
						} else {
							currentBtn.classList.remove('active');
						}
					})
					.catch(error => console.error('Error:', error));
			});
		});
	});
</script>

{% endblock %}

templates/frontend/mail-template.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Thank You for Contacting Us</title>
</head>
<body style="margin:0; padding:0; font-family: Arial, Helvetica, sans-serif; background-color:#f4f4f4;">

  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4; padding:30px 0;">
    <tr>
      <td align="center">

        <!-- Email Container -->
        <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:8px; overflow:hidden; box-shadow:0 2px 6px rgba(0,0,0,0.1);">
          <!-- Header -->
          <tr>
            <td align="center" style="background:green; color:#ffffff; padding:20px 30px;">
              <img src="https://nomadcamel.ng/static/frontend/images/icons/logo-01.png" alt="NOMAD-CAMEL" style="width:auto; height:100px; display:block; margin:auto;">
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:30px; color:#333333; font-size:16px; line-height:1.6;">
              <p>Dear <strong>{{ email }}</strong>,</p>

              <p>We’ve received your message and truly appreciate you taking the time to reach out to us.</p>

              <p>Our support team will review your inquiry and get back to you as soon as possible.  
              In the meantime, feel free to browse our website or simply reply to this email if you have more details to share.</p>

              <p style="margin-top:25px;">Best regards, <br>
              <strong style="color:green">The NOMAD-CAMEL 🐪</strong></p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td align="center" style="background:#f0f0f0; color:#666666; font-size:13px; padding:15px 20px;">
              This is an automated confirmation email. Please do not reply directly to this message.
            </td>
          </tr>
        </table>
        <!-- End Email Container -->

      </td>
    </tr>
  </table>

</body>
</html>

templates/frontend/product.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
NOMAD-CAMEL
{% endblock %}

{% block content %}

<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-t-92 p-b-40"
	style="background-image: url('/static/frontend/images/bg-01.jpg');">
	<h2 class="ltext-105 cl0 txt-center" style="color: green;">
		All Products
	</h2>
</section>

<!-- Product -->
<section class="bg0 p-t-23 p-b-140">
	<div class="container">


		<div class="flex-w flex-sb-m p-b-52">
			<!-- Filter Buttons -->
			<div class="flex-w flex-l-m filter-tope-group m-tb-10">
				<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">All
					Products</button>
				<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".women">Hot & New</button>
				<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".men">Daily Deal</button>
			</div>

			<!-- Search -->
			<div class="flex-w flex-c-m m-tb-10">
				<div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
					<i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
					<i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
					Search
				</div>
			</div>

			<!-- Search Panel -->
			<div class="dis-none panel-search w-full p-t-10 p-b-15">
				<div class="bor8 dis-flex p-l-15">
					<button class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
						<i class="zmdi zmdi-search"></i>
					</button>
					<input class="mtext-107 cl2 size-114 plh2 p-r-15" type="text" name="search-product"
						placeholder="Search">
				</div>
			</div>
		</div>

		<!-- PRODUCTS GRID -->
		<!-- PRODUCTS GRID -->
		<div class="row isotope-grid">
			{% if page_obj %}
			{% for p in page_obj %}
			<div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women">
				<div class="block2">
					<div class="block2-pic hov-img0" style="height: 310px;">
						<img src="{{ p.main_image.url }}" alt="IMG-PRODUCT"
							style="width: 100%; height: 100%; object-fit: cover;">
						<a href="{% url 'frontend:product_details' p.id %}"
							class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04">
							Quick View
						</a>
					</div>
					<div class="block2-txt flex-w flex-t p-t-14">
						<div class="block2-txt-child1 flex-col-l">
							<a href="#" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
								{{ p.name }}
							</a>
							<span class="stext-105 cl3">₦{{ p.price }}</span>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
			{% else %}
			<div class="alert alert-info text-center">No products available at the moment.</div>
			{% endif %}
		</div>

		<!-- Pagination -->
		<div class="flex-c-m flex-w w-full p-t-45">
			<nav aria-label="Page navigation">
				<ul class="pagination justify-content-center">

					{% if page_obj.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
					</li>
					{% endif %}

					{% for num in page_obj.paginator.page_range %}
					{% if page_obj.number == num %}
					<li class="page-item active"><span class="page-link">{{ num }}</span></li>
					{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item"><a
							class="page-link" href="?page={{ num }}">{{ num }}</a></li>
						{% endif %}
						{% endfor %}

						{% if page_obj.has_next %}
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
						</li>
						{% endif %}

				</ul>
			</nav>
		</div>

		<!-- Load More Button -->
		<!-- <div class="flex-c-m flex-w w-full p-t-45">
			<a href="{% url 'frontend:product' %}" id="load-more-btn" class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04">
				Load More
			</a>
			</div> -->
	</div>
</section>


{% endblock %}

templates/frontend/shoping-cart.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title %}
NOMAD-CAMEL - Cart
{% endblock %}

{% block content %}


<!-- breadcrumb -->
<div class="container " style="padding-top: 100px;">
	<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
		<a href="{% url 'index' %}" class="stext-109 cl8 hov-cl1 trans-04">
			Home
			<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
		</a>

		<span class="stext-109 cl4">
			Shoping Cart
		</span>
	</div>
</div>


<!-- Shoping Cart -->
<div class="bg0 p-t-75 p-b-85">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
				<div class="m-l-25 m-r--38 m-lr-0-xl">
					<div class="wrap-table-shopping-cart">
						
						<table class="table-shopping-cart">
							<tr class="table_head">
								<th class="column-1">Product</th>
								<th class="column-2"></th>
								<th class="column-3">Price</th>
								<th class="column-4">Quantity</th>
								<th class="column-5">Total</th>

							</tr>

							{% if items %}
							{% for item in items %}
							<tr class="table_row">
								<td class="column-1">
									<div class="how-itemcart1">
										<img src="{{ item.product.main_image.url }}"
											alt="{{ item.product.name }}">
									</div>
								</td>
								<td class="column-2">{{ item.product.name }}</td>
								<td class="column-3">₦{{ item.product.price }}</td>
								<td class="column-4">
									<form method="post" action="{% url 'backend:update_cart' item.product.id %}">
										{% csrf_token %}

										<div class="wrap-num-product flex-w m-l-auto m-r-0">
											<button type="submit" name="action" value="decrease"
												class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
												<i class="fs-16 zmdi zmdi-minus"></i>
											</button>

											<input class="mtext-104 cl3 txt-center num-product" type="number"
												name="quantity" value="{{ item.quantity }}" min="1">

											<button type="submit" name="action" value="increase"
												class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
												<i class="fs-16 zmdi zmdi-plus"></i>
											</button>
										</div>

										<!-- Main Update button -->
										<button type="submit" name="action" value="update"
											class="btn btn-success btn-sm mt-2">Update</button>

										<!-- Remove button -->
										<button type="submit" name="action" value="remove"
											class="btn btn-danger btn-sm mt-2">Remove</button>
									</form>
								</td>
								<td class="column-5">₦{{ item.subtotal }}</td>
							</tr>

							{% endfor %}
							{% else %}
							<tr>
								<td colspan="5" class="text-center">Your cart is empty.</td>
							</tr>
							{% endif %}


						</table>
					</div>


				</div>
			</div>

			<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
				<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
					<h4 class="mtext-109 cl2 p-b-30">
						Cart Totals
					</h4>




					<div class="flex-w flex-t p-t-27 p-b-33">
						<div class="size-208">
							<span class="mtext-101 cl2">
								Total:
							</span>
						</div>

						<div class="size-209">
							<span class="mtext-110 cl2">
								₦{{ total }}
							</span>
						</div>

					</div>

					<form action="{% url 'backend:checkout' %}" method="get">
						<button type="submit"
							class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" 
							{% if not cart_items %}disabled style="opacity: 0.5; cursor: not-allowed;" {% endif %}>
							Proceed to Checkout
						</button>

					</form>


				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}